/* eslint-disable quotes */
const declValueMap = {
    "0": "0",
    "absolute": "a",
    "auto": "a1",
    "block": "b",
    "bold": "b1",
    "bolder": "b2",
    "both": "b3",
    "break-all": "b4",
    "center": "c",
    "collapse": "c1",
    "default": "d",
    "ellipsis": "e",
    "fixed": "f",
    "gray": "g",
    "hidden": "h",
    "infinite": "i",
    "inherit": "i1",
    "inline": "i2",
    "left": "l",
    "middle": "m",
    "no-repeat": "n",
    "none": "n1",
    "normal": "n2",
    "nowrap": "n3",
    "padding": "p",
    "pointer": "p1",
    "red": "r",
    "relative": "r1",
    "right": "r2",
    "solid": "s",
    "table": "t",
    "tahoma": "t1",
    "tomato": "t2",
    "top": "t3",
    "underline": "u",
    "visible": "v",
    "white": "w",
}
module.exports = declValueMap
